### ISSUE TITLE
Add example

### ISSUE THREAD

**Issue by sibelius** [satya164/react-native-in-app-purchase#2]

**Comment by satya164** [comment]
I'm not actively working on this anymore. Open to hand it over to anyone who wants to continue working on it.

**Comment by macxie** [comment]
how can it work ? i try many times. @satya164 
I am  not an object c  programmer, only react-native developer

**Comment by sibelius** [comment]
@macxie try this one: https://github.com/chirag04/react-native-in-app-utils

**Comment by macxie** [comment]
@sibelius  thx
